import { useEffect, useMemo, useState } from "react";
import { api } from "../api/client.js";
import { Icon, SkeletonRows } from "./AdminUI.jsx";

function scoreSeo(item){const title=item.metaTitle||item.seoTitle||item.title||"";const description=item.metaDescription||item.seoDescription||item.description||"";const checks=[title.length>=30&&title.length<=60,description.length>=80&&description.length<=160,!!(item.keywords||item.slug),!!(item.image||item.socialImage||item.cover),item.visible!==false];return {score:checks.filter(Boolean).length*20,title,description,missing:[!title&&"Titre",!description&&"Description",!(item.keywords||item.slug)&&"Mots-clés",!(item.image||item.socialImage||item.cover)&&"Image sociale"].filter(Boolean)};}

export default function AdminSeoView({notify}){
  const [page,setPage]=useState(null);const [projects,setProjects]=useState([]);const [settings,setSettings]=useState(null);const [saving,setSaving]=useState(false);
  useEffect(()=>{Promise.all([api("/pages/one-page"),api("/projects?all=1"),api("/settings")]).then(([pageData,projectData,settingsData])=>{setPage(pageData);setProjects(projectData);setSettings(settingsData);}).catch(error=>notify(error.message,"error"));},[]);
  const rows=useMemo(()=>{if(!page)return[];const pageRow={id:"page",type:"Page",name:"Home Page",...scoreSeo(page)};const blocks=page.blocks.map(block=>({id:block.id,type:"Section",name:block.label,...scoreSeo({...block.seo,visible:block.visible})}));const projectRows=projects.map(project=>({id:project._id,type:"Projet",name:project.title,...scoreSeo(project)}));return [pageRow,...blocks,...projectRows].sort((a,b)=>b.score-a.score);},[page,projects]);
  if(!page||!settings)return <SkeletonRows/>;const average=Math.round(rows.reduce((sum,row)=>sum+row.score,0)/Math.max(rows.length,1));const excellent=rows.filter(row=>row.score>=80).length;const weak=rows.filter(row=>row.score<60).length;const missing=rows.reduce((sum,row)=>sum+row.missing.length,0);const global=settings.seo||{};
  const updateGlobal=(key,value)=>setSettings(current=>({...current,seo:{...current.seo,[key]:value}}));
  const save=async()=>{setSaving(true);try{setSettings(await api("/settings",{method:"PUT",body:JSON.stringify(settings)}));notify("Configuration SEO enregistrée");}catch(error){notify(error.message,"error");}finally{setSaving(false);}};
  return <><div className="view-heading"><div><span className="admin-kicker">GROWTH / SEO</span><h1>SEO Performance</h1><p>Audit des pages, sections et projets avec priorités d’optimisation.</p></div><button className="button primary" onClick={()=>void save()} disabled={saving}>{saving?"Enregistrement…":"Enregistrer le SEO global"}</button></div><div className="seo-stat-grid"><article className="primary"><span>Score moyen</span><strong>{average}</strong><small>/ 100</small></article><article><span>Bien optimisés</span><strong>{excellent}</strong><small>éléments ≥ 80</small></article><article><span>À améliorer</span><strong>{weak}</strong><small>éléments &lt; 60</small></article><article><span>Champs manquants</span><strong>{missing}</strong><small>actions recommandées</small></article></div><div className="seo-dashboard-grid"><section className="cms-card seo-global-form"><div className="panel-heading"><div><b>Réglages SEO globaux</b><span>Valeurs par défaut</span></div></div>{[["title","Titre par défaut"],["description","Description par défaut"],["keywords","Mots-clés globaux"],["image","Image Open Graph"]].map(([key,label])=><label className="field" key={key}><span>{label}</span>{key==="description"?<textarea rows="4" value={global[key]||""} onChange={event=>updateGlobal(key,event.target.value)}/>:<input value={global[key]||""} onChange={event=>updateGlobal(key,event.target.value)}/>}<small>{key==="title"?`${(global[key]||"").length}/60`:key==="description"?`${(global[key]||"").length}/160`:""}</small></label>)}<div className="google-snippet"><span>{global.title||"Nour Mastouri — Portfolio"}</span><small>https://nourmastouri.com/</small><p>{global.description||"Ajoutez une description SEO globale pour améliorer cet aperçu."}</p></div></section><section className="cms-card seo-ranking"><div className="panel-heading"><div><b>Classement SEO</b><span>Du mieux optimisé au plus faible</span></div></div><div className="seo-ranking-list">{rows.map((row,index)=><article key={row.id}><span className="rank">{index+1}</span><div><b>{row.name}</b><small>{row.type} · {row.missing.length?`Manque: ${row.missing.join(", ")}`:"Complet"}</small></div><div className={`score-ring score-${row.score>=80?"good":row.score>=60?"medium":"bad"}`}>{row.score}</div></article>)}</div></section></div><section className="cms-card seo-actions"><div><Icon name="warning"/><span><b>Priorités SEO</b><small>Commencez par les éléments avec un score inférieur à 60.</small></span></div>{rows.filter(row=>row.score<60).slice(0,5).map(row=><span key={row.id}><b>{row.name}</b> — {row.missing.join(", ")||"Contenu trop court"}</span>)}</section></>;
}
