import { useEffect, useRef, useState } from "react";
import { api } from "../api/client.js";
import { Icon, SkeletonRows } from "./AdminUI.jsx";

const defaults = { background: "#eeeae3", text: "#11110f", scrollBackground: "#11110f", scrollText: "#ffffff", blur: 12, height: 76, sticky: true, border: "#cfc9bf" };

export default function AdminMenuView({ notify }) {
  const [settings, setSettings] = useState(null); const [scrolled, setScrolled] = useState(false); const [saving, setSaving] = useState(false); const frameRef = useRef(null);
  useEffect(() => { api("/settings").then(setSettings).catch(error => notify(error.message, "error")); }, []);
  const paint = () => {
    const doc = frameRef.current?.contentDocument; const header = doc?.querySelector(".site-header"); if (!header || !settings) return;
    doc.querySelector("main")?.remove(); doc.querySelector(".footer")?.remove(); doc.querySelector(".floating-back-to-top")?.remove();
    const style = { ...defaults, ...(settings.menuStyle || {}) };
    Object.assign(header.style, { position: "relative", top: "0", background: scrolled ? style.scrollBackground : style.background, color: scrolled ? style.scrollText : style.text, minHeight: `${style.height}px`, backdropFilter: `blur(${style.blur}px)`, borderBottom: `1px solid ${style.border}` });
    header.querySelectorAll("a,button").forEach(node => { node.style.color = scrolled ? style.scrollText : style.text; });
    doc.onclick = event => { if (event.target.closest("a,button,form")) { event.preventDefault(); event.stopPropagation(); } };
    doc.body.style.margin = "0"; doc.body.style.minHeight = `${style.height}px`; doc.body.style.overflow = "hidden";
  };
  useEffect(paint, [settings, scrolled]);
  if (!settings) return <SkeletonRows/>;
  const style = { ...defaults, ...(settings.menuStyle || {}) };
  const updateStyle = (key, value) => setSettings(current => ({ ...current, menuStyle: { ...defaults, ...(current.menuStyle || {}), [key]: value } }));
  const updateItem = (index, key, value) => setSettings(current => ({ ...current, menu: current.menu.map((item, i) => i === index ? { ...item, [key]: value } : item) }));
  const move = (index, direction) => setSettings(current => { const menu = [...current.menu]; const target = index + direction; if (target < 0 || target >= menu.length) return current; [menu[index], menu[target]] = [menu[target], menu[index]]; return { ...current, menu: menu.map((item, i) => ({ ...item, sortOrder: i })) }; });
  const save = async () => { setSaving(true); try { setSettings(await api("/settings", { method: "PUT", body: JSON.stringify(settings) })); notify("Menu et styles enregistrés"); } catch (error) { notify(error.message, "error"); } finally { setSaving(false); } };
  return <><div className="view-heading"><div><span className="admin-kicker">DESIGN / MENU</span><h1>Menu & Navigation</h1><p>Contenu, ordre, apparence initiale et style après scroll.</p></div><button className="button primary" disabled={saving} onClick={() => void save()}>{saving ? "Enregistrement…" : "Enregistrer"}</button></div><div className="menu-preview-toolbar"><button className={!scrolled ? "active" : ""} onClick={() => setScrolled(false)}>En haut de page</button><button className={scrolled ? "active" : ""} onClick={() => setScrolled(true)}>Après scroll</button></div><div className="menu-real-preview"><iframe ref={frameRef} title="Aperçu du menu" src="/?menu-preview=1" onLoad={paint}/></div><div className="menu-admin-grid"><section className="cms-card menu-content-editor"><div className="panel-heading"><div><b>Liens du menu</b><span>Ordre et visibilité</span></div></div>{settings.menu.map((item,index) => <div className="advanced-menu-row" key={index}><span className="drag-index">{String(index+1).padStart(2,"0")}</span><input value={item.label} onChange={event => updateItem(index,"label",event.target.value)}/><input value={item.url} onChange={event => updateItem(index,"url",event.target.value)}/><label><input type="checkbox" checked={item.visible !== false} onChange={event => updateItem(index,"visible",event.target.checked)}/> Visible</label><button disabled={!index} onClick={() => move(index,-1)}>↑</button><button disabled={index === settings.menu.length-1} onClick={() => move(index,1)}>↓</button><button className="danger-link" onClick={() => setSettings(current => ({ ...current, menu: current.menu.filter((_,i) => i !== index) }))}><Icon name="trash"/></button></div>)}<button className="button secondary" onClick={() => setSettings(current => ({ ...current, menu: [...current.menu,{label:"Nouveau lien",url:"#",visible:true,sortOrder:current.menu.length}] }))}><Icon name="plus"/> Ajouter un lien</button></section><section className="cms-card menu-style-editor"><div className="panel-heading"><div><b>Styles du menu</b><span>Normal et scroll</span></div></div>{[["background","Fond initial","color"],["text","Texte initial","color"],["scrollBackground","Fond après scroll","color"],["scrollText","Texte après scroll","color"],["border","Bordure","color"],["height","Hauteur","number"],["blur","Flou arrière-plan","number"]].map(([key,label,type]) => <label className="style-control" key={key}><span>{label}</span><input type={type} value={style[key]} onChange={event => updateStyle(key,type === "number" ? Number(event.target.value) : event.target.value)}/><output>{style[key]}{type === "number" ? "px" : ""}</output></label>)}<label className="visibility-toggle"><input type="checkbox" checked={style.sticky} onChange={event => updateStyle("sticky",event.target.checked)}/> Menu sticky</label></section></div></>;
}
