import { useEffect, useState } from "react";
import { api, mediaUrl } from "../api/client.js";
import { Icon, SkeletonRows } from "./AdminUI.jsx";

export default function AdminProfileView({ notify }) {
  const [settings, setSettings] = useState(null); const [saving, setSaving] = useState(false);
  useEffect(() => { api("/settings").then(setSettings).catch(error => notify(error.message, "error")); }, []);
  if (!settings) return <SkeletonRows/>;
  const profile = settings.profile || {};
  const update = (key, value) => setSettings(current => ({ ...current, profile: { ...current.profile, [key]: value } }));
  const upload = async file => { if (!file) return; const body = new FormData(); body.append("file", file); try { const item = await api("/media", { method: "POST", body }); update("avatar", item.url); notify("Photo de profil importée"); } catch (error) { notify(error.message, "error"); } };
  const save = async () => { setSaving(true); try { setSettings(await api("/settings", { method: "PUT", body: JSON.stringify(settings) })); notify("Profil enregistré"); } catch (error) { notify(error.message, "error"); } finally { setSaving(false); } };
  return <><div className="view-heading"><div><span className="admin-kicker">ACCOUNT / PROFILE</span><h1>Profil administrateur</h1><p>Identité, coordonnées, liens professionnels et préférences du CMS.</p></div><button className="button primary" onClick={() => void save()} disabled={saving}>{saving ? "Enregistrement…" : "Enregistrer"}</button></div><div className="admin-profile-grid"><aside className="cms-card profile-identity"><div className="profile-avatar-large">{profile.avatar ? <img src={mediaUrl(profile.avatar)} alt="Profil"/> : (profile.name || "NM").split(" ").map(value => value[0]).join("").slice(0,2)}</div><h2>{profile.name || "Nour Mastouri"}</h2><p>{profile.role}</p><label className="button secondary"><Icon name="upload"/> Changer la photo<input type="file" accept="image/jpeg,image/png,image/webp" onChange={event => void upload(event.target.files?.[0])}/></label><span>JPG, PNG ou WEBP · 10 Mo max.</span></aside><section className="cms-card profile-form">{[["name","Nom complet"],["role","Fonction"],["email","Email"],["phone","Téléphone"],["location","Localisation"],["website","Site web"],["linkedin","LinkedIn"],["behance","Behance"]].map(([key,label]) => <label className="field" key={key}><span>{label}</span><input value={profile[key] || ""} onChange={event => update(key,event.target.value)}/></label>)}<label className="field full"><span>Biographie</span><textarea rows="6" value={profile.bio || ""} onChange={event => update("bio", event.target.value)}/></label><label className="field"><span>Langue du CMS</span><select value={profile.adminLanguage || "fr"} onChange={event => update("adminLanguage", event.target.value)}><option value="fr">Français</option><option value="en">English</option></select></label><label className="field"><span>Fuseau horaire</span><input value={profile.timezone || "Africa/Tunis"} onChange={event => update("timezone",event.target.value)}/></label></section></div></>;
}
