import { useEffect, useRef, useState } from "react";
import { API_URL, api } from "../api/client.js";
import { EmptyState, Icon, SkeletonRows } from "./AdminUI.jsx";
import { formatBytes, formatDate } from "./adminUtils.js";

export default function AdminToolsView({ notify }) {
  const [status,setStatus]=useState(null); const [error,setError]=useState(""); const [busy,setBusy]=useState(""); const [validation,setValidation]=useState(null); const fileRef=useRef(null);
  const load=()=>api("/backup/status").then(setStatus).catch(err=>setError(err.message));
  useEffect(()=>{void load();},[]);
  const backup=async()=>{setBusy("backup");try{const response=await fetch(`${API_URL}/backup/export`,{headers:{Authorization:`Bearer ${localStorage.getItem("nour_admin_token")}`}});if(!response.ok)throw new Error(`HTTP ${response.status}`);const blob=await response.blob();const url=URL.createObjectURL(blob);const link=document.createElement("a");link.href=url;link.download=`nour-cms-backup-${new Date().toISOString().replace(/[:.]/g,"-")}.json`;link.click();URL.revokeObjectURL(url);notify("Backup complet téléchargé");}catch(err){notify(err.message,"error");}finally{setBusy("");}};
  const validate=async file=>{if(!file)return;setBusy("validate");try{const json=JSON.parse(await file.text());const result=await api("/backup/validate",{method:"POST",body:JSON.stringify(json)});setValidation(result);notify("Backup valide");}catch(err){setValidation({valid:false,errors:[err.message]});notify("Backup invalide","error");}finally{setBusy("");}};
  const sync=async(type)=>{setBusy(type);try{const result=await api(type==="pages"?"/pages/sync-site":"/media/sync-public",{method:"POST"});notify(type==="pages"?`${result.updated} sections synchronisées`:`${result.imported} médias importés`);await load();}catch(err){notify(err.message,"error");}finally{setBusy("");}};
  if(error)return <EmptyState icon="warning" title="Diagnostic indisponible" text={error} action={<button onClick={load}>Réessayer</button>}/>;
  if(!status)return <SkeletonRows/>;
  return <><div className="view-heading"><div><span className="admin-kicker">SYSTEM / MAINTENANCE</span><h1>Tools & Backup</h1><p>Santé du CMS, sauvegarde, validation et synchronisation des contenus.</p></div><button className="button primary" onClick={()=>void backup()} disabled={!!busy}><Icon name="download"/> {busy==="backup"?"Export…":"Créer un backup"}</button></div><div className="system-health-card cms-card"><div className="health-main"><i/><div><b>Système opérationnel</b><span>MongoDB connectée · contrôle {formatDate(status.checkedAt)}</span></div><button onClick={()=>void load()}>Actualiser</button></div><div className="health-stats">{Object.entries(status.counts).map(([key,value])=><div key={key}><strong>{value}</strong><span>{key}</span></div>)}<div><strong>{formatBytes(status.mediaBytes)}</strong><span>stockage média</span></div></div></div><div className="tools-pro-grid"><section className="cms-card tool-pro-card"><Icon name="archive" size={26}/><h2>Backup JSON complet</h2><p>Projets, One Page, médias, réglages, blocs sauvegardés et globaux.</p><button className="button secondary" onClick={()=>void backup()}>Télécharger maintenant</button></section><section className="cms-card tool-pro-card"><Icon name="check" size={26}/><h2>Vérifier un backup</h2><p>Contrôle la version et la structure avant toute restauration manuelle.</p><button className="button secondary" onClick={()=>fileRef.current?.click()}>{busy==="validate"?"Vérification…":"Choisir un fichier"}</button><input ref={fileRef} type="file" accept="application/json" hidden onChange={event=>void validate(event.target.files?.[0])}/>{validation&&<div className={`backup-validation ${validation.valid?"success":"error"}`}>{validation.valid?`Valide · ${validation.summary.projects} projets · ${validation.summary.pages} pages`:validation.errors.join(" · ")}</div>}</section><section className="cms-card tool-pro-card"><Icon name="restore" size={26}/><h2>Synchroniser le contenu</h2><p>Réimporte la structure actuelle du One Page dans le CMS.</p><button className="button secondary" disabled={!!busy} onClick={()=>void sync("pages")}>Synchroniser les sections</button></section><section className="cms-card tool-pro-card"><Icon name="media" size={26}/><h2>Scanner les médias</h2><p>Ajoute à la médiathèque les images existantes absentes de MongoDB.</p><button className="button secondary" disabled={!!busy} onClick={()=>void sync("media")}>Scanner les assets</button></section></div></>;
}
