import { useEffect, useState } from "react";
import { API_URL, api } from "../api/client.js";
import { EmptyState, Icon, SkeletonRows } from "./AdminUI.jsx";

const defaults = {
  theme: { accent: "#d9ff43", background: "#eeeae3", foreground: "#11110f", panel: "#f7f5f0" },
  profile: { name: "", role: "", email: "", avatar: "", bio: "" },
  seo: { title: "", description: "", keywords: "", image: "" },
  menu: [], customCss: "", footer: ""
};

export default function AdminSettingsView({ section = "appearance", notify }) {
  const [settings, setSettings] = useState(defaults);
  const [loading, setLoading] = useState(true);
  const [saving, setSaving] = useState(false);
  const [error, setError] = useState("");
  useEffect(() => { api("/settings").then(data => setSettings(current => ({ ...current, ...data, theme: { ...current.theme, ...data.theme }, profile: { ...current.profile, ...data.profile }, seo: { ...current.seo, ...data.seo } }))).catch(error => setError(error.message)).finally(() => setLoading(false)); }, []);
  const update = (key, value) => setSettings(current => ({ ...current, [key]: value }));
  const updateGroup = (group, key, value) => setSettings(current => ({ ...current, [group]: { ...current[group], [key]: value } }));
  async function save() { setSaving(true); try { const saved = await api("/settings", { method: "PUT", body: JSON.stringify(settings) }); setSettings(saved); notify("Réglages enregistrés"); } catch (requestError) { notify(requestError.message, "error"); } finally { setSaving(false); } }
  async function backup() { try { const response = await fetch(`${API_URL}/backup/export`, { headers: { Authorization: `Bearer ${localStorage.getItem("nour_admin_token")}` } }); if (!response.ok) throw new Error(`HTTP ${response.status}`); const blob = await response.blob(); const url = URL.createObjectURL(blob); const link = document.createElement("a"); link.href = url; link.download = `nour-cms-backup-${new Date().toISOString().slice(0, 10)}.json`; link.click(); URL.revokeObjectURL(url); notify("Backup téléchargé"); } catch (requestError) { notify(requestError.message, "error"); } }
  if (loading) return <SkeletonRows count={5}/>;
  if (error) return <EmptyState icon="warning" title="Réglages indisponibles" text={error}/>;
  const titles = { appearance: ["Appearance", "Couleurs et CSS du site"], header: ["Header", "Identité et structure du header"], navigation: ["Menus", "Navigation principale"], footer: ["Footer", "Contenu global du footer"], seo: ["SEO", "Référencement global"], tools: ["Tools & Backup", "Outils de maintenance"], profile: ["Profile", "Informations administrateur"] };
  const [title, description] = titles[section] || titles.appearance;
  return <>
    <div className="view-heading settings-heading"><div><span className="admin-kicker">SETTINGS / {section.toUpperCase()}</span><h1>{title}</h1><p>{description}</p></div><button className="button primary" onClick={() => void save()} disabled={saving}>{saving ? "Enregistrement…" : "Enregistrer"}</button></div>
    {section === "appearance" && <div className="settings-grid"><section className="cms-card settings-card"><div className="panel-heading"><div><b>Theme colors</b><span>Design tokens admin</span></div></div>{["accent", "background", "foreground", "panel"].map(key => <label className="color-field" key={key}><span>{key}</span><input type="color" value={settings.theme[key]} onChange={event => updateGroup("theme", key, event.target.value)}/><input value={settings.theme[key]} onChange={event => updateGroup("theme", key, event.target.value)}/></label>)}</section><section className="cms-card settings-card"><div className="panel-heading"><div><b>Custom CSS</b><span>Stored with the site settings</span></div></div><textarea className="css-editor" value={settings.customCss || ""} onChange={event => update("customCss", event.target.value)} placeholder=".hero { ... }"/></section></div>}
    {section === "header" && <section className="cms-card settings-card settings-form-card"><div className="panel-heading"><div><b>Header global</b><span>Brand identity visible on the site</span></div></div><label className="field"><span>Logo text</span><input value={settings.logoText || ""} onChange={event => update("logoText", event.target.value)}/></label><label className="field"><span>Site title</span><input value={settings.siteTitle || ""} onChange={event => update("siteTitle", event.target.value)}/></label><label className="field"><span>Site description</span><textarea rows="5" value={settings.siteDescription || ""} onChange={event => update("siteDescription", event.target.value)}/></label></section>}
    {section === "navigation" && <section className="cms-card settings-card"><div className="panel-heading"><div><b>Menu principal</b><span>Links and order</span></div></div><div className="menu-editor">{settings.menu.map((item, index) => <div className="menu-row" key={`${item.label}-${index}`}><input value={item.label} onChange={event => setSettings(current => ({ ...current, menu: current.menu.map((entry, i) => i === index ? { ...entry, label: event.target.value } : entry) }))}/><input value={item.url} onChange={event => setSettings(current => ({ ...current, menu: current.menu.map((entry, i) => i === index ? { ...entry, url: event.target.value } : entry) }))}/><button className="icon-button" onClick={() => setSettings(current => ({ ...current, menu: current.menu.filter((_, i) => i !== index) }))}><Icon name="trash"/></button></div>)}<button className="button secondary" onClick={() => setSettings(current => ({ ...current, menu: [...current.menu, { label: "New link", url: "#", sortOrder: current.menu.length }] }))}><Icon name="plus"/> Ajouter un lien</button></div></section>}
    {section === "seo" && <section className="cms-card settings-card settings-form-card"><div className="panel-heading"><div><b>SEO global</b><span>Default metadata</span></div></div>{[["title", "Meta title"], ["description", "Meta description"], ["keywords", "Keywords"], ["image", "Social image URL"]].map(([key, label]) => <label className="field" key={key}><span>{label}</span>{key === "description" ? <textarea rows="4" value={settings.seo[key]} onChange={event => updateGroup("seo", key, event.target.value)}/> : <input value={settings.seo[key]} onChange={event => updateGroup("seo", key, event.target.value)}/>}</label>)}</section>}
    {section === "footer" && <section className="cms-card settings-card settings-form-card"><div className="panel-heading"><div><b>Footer global</b><span>Contenu affiché en bas du site</span></div></div><label className="field"><span>Footer content</span><textarea rows="10" value={settings.footer || ""} onChange={event => update("footer", event.target.value)}/></label></section>}
    {section === "profile" && <section className="cms-card settings-card settings-form-card"><div className="panel-heading"><div><b>Admin profile</b><span>Account information</span></div></div>{[["name", "Name"], ["role", "Role"], ["email", "Email"], ["avatar", "Avatar URL"]].map(([key, label]) => <label className="field" key={key}><span>{label}</span><input value={settings.profile[key]} onChange={event => updateGroup("profile", key, event.target.value)}/></label>)}<label className="field"><span>Bio</span><textarea rows="5" value={settings.profile.bio} onChange={event => updateGroup("profile", "bio", event.target.value)}/></label></section>}
    {section === "tools" && <section className="settings-grid"><section className="cms-card settings-card settings-form-card"><div className="panel-heading"><div><b>Database backup</b><span>Export all CMS records as JSON</span></div></div><div className="settings-tool-body"><p>Projects, pages, media metadata and site settings are included.</p><button className="button primary" onClick={() => void backup()}><Icon name="download"/> Download backup</button></div></section><section className="cms-card settings-card settings-form-card"><div className="panel-heading"><div><b>Footer content</b><span>Global footer text</span></div></div><textarea className="footer-editor" rows="8" value={settings.footer || ""} onChange={event => update("footer", event.target.value)}/></section></section>}
  </>;
}
